### ISSUE TITLE
Actor crashed!

### ISSUE THREAD

**Issue by nicka** [vasilakisfil/api_bomb#2]
Is there something we can do about the crashing actors?

```
I, [2016-01-02T23:51:14.124203 #6779]  INFO -- : Starts firing requests
E, [2016-01-02T23:51:31.355284 #6779] ERROR -- : Actor crashed!
SocketError: getaddrinfo: nodename nor servname provided, or not known
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `initialize'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `open'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `connect'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/connection.rb:33:in `initialize'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/client.rb:56:in `new'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/client.rb:56:in `perform'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/client.rb:36:in `request'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/chainable.rb:74:in `request'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-0.9.8/lib/http/chainable.rb:18:in `get'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/api_bomb-0.1.3/lib/api_bomb/fighter.rb:18:in `block in fire'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/api_bomb-0.1.3/lib/api_bomb/fighter.rb:17:in `fire'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/calls.rb:28:in `public_send'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/calls.rb:28:in `dispatch'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/call/sync.rb:16:in `dispatch'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/cell.rb:50:in `block in dispatch'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/cell.rb:76:in `block in task'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/actor.rb:339:in `block in task'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/task.rb:44:in `block in initialize'
    /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by nicka** [comment]
@vasilakisfil Do you have an idea?

**Comment by vasilakisfil** [comment]
@nicka sorry for my late response. As far as I can see the actor cannot access the IP/address you provided. What do you mean about doing something? Do you have in mind a specific behavior when an actor crashes ?
